### PR TITLE
Initial Chicken Scheme Support

### PR DESCRIPTION
**Pull request by dleslie**
If you are able, could you please give it a smoke test before merging?

I've given it a look over myself; but I must admit I'm quite weary from the late, short nights with my newborn, and I am not totally familiar with Geiser's full functionality.

### CODE REVIEW

**Comment by dleslie** [comment]
I apologise for the long delay; I've been swamped with other things.

**Comment by jaor** [comment]
no need to apologize :) happy new year!

**Comment by dleslie** [comment]
Two things:

1. It appears that fixing the behaviour where module exports cannot be redefined will require a patch to Chicken; as Chicken just doesn't support that behaviour.

2. The autodoc bug is almost certainly a timing issue. After greatly improving performance I find it difficult to reproduce; so much so that I have yet to.

**Comment by dleslie** [comment]
There doesn't appear to be any way to suppress the aforementioned output of load-file short of parsing the output and ignoring it in that instance.

**Comment by dleslie** [comment]
It's feeling fairly solid now. Basically it's missing rebinding of exported module definitions, and the functionality that supports jumping to the location in source where a symbol was bound. I don't believe either can be supported by Chicken, but I've posed a question about the former to the chicken-hackers mailing list.

However, the following works:

```scheme
(module foo (baz)
  (import chicken scheme)
  (define bar 1)
  (define (baz) bar))
```
`C-x e` at `(baz)` shows `1`, as expected.

If you change it such that it is:

```scheme
(module foo (baz)
  (import chicken scheme)
  (define bar 2)
  (define (baz) bar))
```

Then `C-x e` at `(define bar )` followed by the same at `(baz)` will give you the expected output of `2`.

**Comment by dleslie** [comment]
That is to say, *non-exported* module bindings can be rebound.

**Comment by jaor** [comment]
excellent.  i'll try to give a final look at the PR in the following few
days and merge it into master.  then i'll review the user manual to
insert at appropriate places info specific to the chicken implementation
and (if you don't see any problem with that), a new geiser release with
chicken support (which will make me very happy since the whole design
was geared towards making new schemes possible!).

**Comment by dleslie** [comment]
May I be so presumptuous as to request that you name the release
"Freija", in honour of my three-month old daughter who shared my lap
with the laptop as I wrote much of the Chicken Scheme support?

Thanks!
-Dan

jao <notifications@github.com> writes:

> excellent.  i'll try to give a final look at the PR in the following few
> days and merge it into master.  then i'll review the user manual to
> insert at appropriate places info specific to the chicken implementation
> and (if you don't see any problem with that), a new geiser release with
> chicken support (which will make me very happy since the whole design
> was geared towards making new schemes possible!).
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jaor/geiser/pull/48#issuecomment-72365953

-- 
-Dan Leslie

**Comment by wasamasa** [comment]
Is there any plan on how to achieve support for jumping to the source of a definition? If you could find out to which egg/module a library belongs and have a destination on disk with sources of it, I could imagine that simplicistic approach to work out.

**Comment by dleslie** [comment]
I will pose the question to chicken-hackers, but I don't believe that it is likely to be answered favorably. The support is there for compiled code only, but disabled by default.Alternatively, I am mulling over a projectile-chicken concept that would attempt much of the behaviour found in projectile-rails.-Dan                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Vasilij SchneidermannSent: Sunday, February 8, 2015 3:28 AMTo: jaor/geiserReply To: jaor/geiserCc: Dan LeslieSubject: Re: [geiser] Initial Chicken Scheme Support (#48)Is there any plan on how to achieve support for jumping to the source of a definition? If you could find out to which egg/module a library belongs and have a destination on disk with sources of it, I could imagine that simplicistic approach to work out.

—Reply to this email directly or view it on GitHub.

**Comment by jaor** [comment]
Dan: i've merged this branch with the current master and pushed it to github in the new 'chicken' branch.  Completion is not working for me, neither in the repl nor in scheme buffers: i get this error:

```
Debugger entered--Lisp error: (wrong-type-argument listp "#<unspecified>")
  car("#<unspecified>")
  (setq e (car --dolist-tail--))
  (while --dolist-tail-- (setq e (car --dolist-tail--)) (if (member e result) nil (setq result (cons e result))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- lst) e) (while --dolist-tail-- (setq e (car --dolist-tail--)) (if (member e result) nil (setq result (cons e result))) (setq --dolist-tail-- (cdr --dolist-tail--))) (setq e nil) (nreverse result))
  (let (result) (let ((--dolist-tail-- lst) e) (while --dolist-tail-- (setq e (car --dolist-tail--)) (if (member e result) nil (setq result (cons e result))) (setq --dolist-tail-- (cdr --dolist-tail--))) (setq e nil) (nreverse result)))
  geiser--del-dups("#<unspecified>")
  geiser-completion--symbol-list("defi")
  (if modules (geiser-completion--module-list prefix) (geiser-completion--symbol-list prefix))
  geiser-completion--complete("defi" nil)
  (and prefix (geiser-completion--complete prefix module))
  (let* ((beg (geiser-completion--symbol-begin module)) (end (or (geiser-completion--prefix-end beg module) beg)) (prefix (and (> end beg) (buffer-substring-no-properties beg end))) (prefix (and prefix (if (string-match "\\([^-]+\\)-" prefix) (match-string 1 prefix) prefix))) (cmps (and prefix (geiser-completion--complete prefix module)))) (and cmps (list beg end cmps)))
  (progn (set-syntax-table scheme-mode-syntax-table) (let* ((beg (geiser-completion--symbol-begin module)) (end (or (geiser-completion--prefix-end beg module) beg)) (prefix (and (> end beg) (buffer-substring-no-properties beg end))) (prefix (and prefix (if (string-match "\\([^-]+\\)-" prefix) (match-string 1 prefix) prefix))) (cmps (and prefix (geiser-completion--complete prefix module)))) (and cmps (list beg end cmps))))
  (unwind-protect (progn (set-syntax-table scheme-mode-syntax-table) (let* ((beg (geiser-completion--symbol-begin module)) (end (or (geiser-completion--prefix-end beg module) beg)) (prefix (and (> end beg) (buffer-substring-no-properties beg end))) (prefix (and prefix (if (string-match "\\([^-]+\\)-" prefix) (match-string 1 prefix) prefix))) (cmps (and prefix (geiser-completion--complete prefix module)))) (and cmps (list beg end cmps)))) (save-current-buffer (set-buffer buffer) (set-syntax-table table)))
  (let ((table (syntax-table)) (buffer (current-buffer))) (unwind-protect (progn (set-syntax-table scheme-mode-syntax-table) (let* ((beg (geiser-completion--symbol-begin module)) (end (or (geiser-completion--prefix-end beg module) beg)) (prefix (and (> end beg) (buffer-substring-no-properties beg end))) (prefix (and prefix (if ... ... prefix))) (cmps (and prefix (geiser-completion--complete prefix module)))) (and cmps (list beg end cmps)))) (save-current-buffer (set-buffer buffer) (set-syntax-table table))))
  geiser-completion--thing-at-point(nil nil)
  geiser-completion--for-symbol()
  completion--capf-wrapper(geiser-completion--for-symbol all)
  run-hook-wrapped(completion--capf-wrapper geiser-completion--for-symbol all)
  completion-at-point()
  call-interactively(completion-at-point nil nil)
  command-execute(completion-at-point)
```

Does it happen to you?

**Comment by dleslie** [comment]
I haven't seen that yet; I'll pull your merged branch and give it a shot.

Also worth noting is that I am using chicken 4.9.0

**Comment by jaor** [comment]
i'm using 4.9.0 too... maybe we should make that the minimum required
version in the release docs?

**Comment by jaor** [comment]
i've also just noticed the same error happens every now and then with (i think) autodoc (which works fine the rest of the time).

**Comment by dleslie** [comment]
Ok, confirmed. I booted without my init.el and loaded it directly; something else was inhibiting that error and I haven't a clue what.

I'll fix it in this raw environment.

**Comment by dleslie** [comment]
Alright, that's fixed.

It looks like I was still loading auto-complete, which was feeding in symbols and inhibiting that error when I pressed C-M-i, somehow. Tested without AC and it appears good.

**Comment by jaor** [comment]
aha, this is working much better now.

another quirk: when i ask for documentation for `define` (e.g., using
C-c C-d d), i'm presented with the seemingly unrelated info pasted below
and the link to the manual points to
http://api.call-cc.org/doc/qobischeme-ui/define. other identifiers seem
to work well, though.

```
((r5rs r7rs):define <macro> ...)

= Node: define  =

-- procedure: (define stalin? #f)
-- procedure: (char-alphanumeric? char)
-- procedure: (beginning-of-word? string position)
-- procedure: (end-of-word? string position)
-- procedure: (string-backward-word string position)
-- procedure: (string-kill-word string position)
-- procedure: (string-forward-word string position)
-- procedure: (string-backward-kill-word string position)
-- procedure: (string-insert-character character)
-- procedure: (string-beginning-of-line string position)
-- procedure: (string-backward-char string position)
-- procedure: (string-delete-char string position)
-- procedure: (string-end-of-line string position)
-- procedure: (string-forward-char string position)
-- procedure: (string-kill-line string position)
-- procedure: (string-backward-delete-char string position)

Miscellaneous functions. These probably belong elsewhere.

[manual] [source]
```

**Comment by dleslie** [comment]
This is a quirk in Chicken Doc. It presents information found in the Wiki,
and it doesn't have a fully complete database of Scheme functions. The
"Node" is the discovered node in Chicken Doc that looks like the symbol,
and the list the follows is Chicken Doc's best guess for possible intended
matches. But, because the documentation for standard symbols is incomplete
it's missing some critical things, notably define.

-Dan

**Comment by dleslie** [comment]
IE, from the command line:

dleslie@shodan ~/Workspace $ chicken-doc define
path: (qobischeme-ui define)

-- procedure: (define stalin? #f)
-- procedure: (char-alphanumeric? char)
-- procedure: (beginning-of-word? string position)
-- procedure: (end-of-word? string position)
-- procedure: (string-backward-word string position)
-- procedure: (string-kill-word string position)
-- procedure: (string-forward-word string position)
-- procedure: (string-backward-kill-word string position)
-- procedure: (string-insert-character character)
-- procedure: (string-beginning-of-line string position)
-- procedure: (string-backward-char string position)
-- procedure: (string-delete-char string position)
-- procedure: (string-end-of-line string position)
-- procedure: (string-forward-char string position)
-- procedure: (string-kill-line string position)
-- procedure: (string-backward-delete-char string position)

Miscellaneous functions. These probably belong elsewhere.

**Comment by dleslie** [comment]
One thing that I played with and perhaps we should consider putting back
in, is creating additional documentation from the completion information. I
get that from apropos, which pulls it from the environment itself. However,
it also lacks any useful information for a great number of symbols; like
define:

```scheme
#;4> (apropos-information-list 'define #:macros? #t)
((type-checks#check-defined-value procedure loc161 obj162 . args163)
(set-module-undefined-list! procedure x241294 y242295)
(type-errors#error-defined-value procedure loc112 obj113 tag114 .
tmp111115) (module-undefined-list procedure x241291) (define-reader-ctor
procedure spec2644 proc2645) (define . macro) (define-syntax . macro)
(define-constant . macro) (define-record . macro) (define-values . macro)
(define-inline . macro) (define-record-printer . macro) (define-record-type
. macro) (define-for-syntax . macro) (define-compiler-syntax . macro)
(define-interface . macro) (define-specialization . macro) (define-type .
macro))
```

Note how all the macros have no useful information.

-Dan

**Comment by jaor** [comment]
that might be interesting, but we can leave it for a future PR, so that
we can get in this big one first.  in the `chicken` branch, you'll see
i've added a commit with some documentation and little nits (mainly
trailing whitespace).  if you don't see anything strange there
(https://github.com/jaor/geiser/commit/4cb3b9696e7a0bd4fa12c3edca857ea4ddb13b88),
we can merge it into master, and then prepare Geiser 0.7 "Freija"
(greatest version nickname ever for geiser, btw :))

i guess you want to keep the full set of separate commits in master?
otherwise, we could rebase yours into one to keep the history cleaner,
but i'm happy if you prefer not to lose it in the merge.

**Comment by dleslie** [comment]
Nothing alarming popped out at me, and I greatly appreciate the honorarium
for Freija. :D

Rebasing to one commit is fine; I don't think there's anything of strong
value that would be lost. I'll consider branching with my fork and keep the
history there, regardless.

Take care,
-Dan

**Comment by jaor** [comment]
On Mon, Feb 09 2015, Dan Leslie wrote:

> Nothing alarming popped out at me, and I greatly appreciate the
> honorarium for Freija. :D

she (and you!) definitely deserves it :)

> Rebasing to one commit is fine; I don't think there's anything of
> strong value that would be lost. I'll consider branching with my fork
> and keep the history there, regardless.

okay: i've squashed all your hard work into a single patch and pushed it
together with mine to master (my chicken branch still contains all your
original history, and i won't delete it for the time being).

let's give it a try and in a couple of days i can release 0.7.

we can close this PR, but perhaps you'd like to open a few issues
collecting suggestions or problems that have been discussed in this
thread?

thanks a lot!

**Comment by jiahut** [comment]
It will fault with company-mode when switch to chicken implement.

**Comment by dleslie** [comment]
Does it work if you first run chicken?
IE,
M-x run-chicken

**Comment by jiahut** [comment]
@dleslie 
I'm sure that ` * Chicken REPL * ` buffer  is running. 
It will be ok when switch to guile implement.

**Comment by dleslie** [comment]
Huh, curious. I'll see if I can reproduce that failure.

**Comment by dleslie** [comment]
Nope, I can't reproduce. Completion worked well with the company-capf backend.

At the bottom of the scheme buffer does it show that Chicken is the scheme being used? You can force it to use Chicken by either setting ```geiser-default-implementation``` to ```chicken```, or by putting ```chicken``` ahead of ```guile``` in ```geiser-active-implementations```, or by adding the following to the top of your scheme file:

```scheme
;; chicken
```

Actually, so long as ```chicken``` occurs in the first line of the file it should be detected as a chicken scheme file.

**Comment by dleslie** [comment]
That is to say, it sounds to me like Geiser is detecting the buffer to be a Guile buffer and not a Chicken buffer.

This is sort of a quirk with Geiser, I think. I would almost rather have it ask which Scheme to use if it can't determine for certain and if ```geiser-default-implementation``` isn't set.

**Pull request closed without merging**
