### PR TITLE
Make geiser-chicken-required-modules customizable

### PR DESCRIPTION
**Pull request by dieggsy**
Some people (such as myself) may not want to start with these modules (or any) by default.

### CODE REVIEW

**Comment by jaor** [comment]
thanks @dieggsy, it looks good to me. @dleslie do you think we can merge this one?

**Comment by dleslie** [comment]
Without those modules the geiser module will not work. IE, `apropos` is critical.

**Comment by dieggsy** [comment]
@dleslie what exactly won't work? I set this to nil and (on first impression) it seems like what I want. I still get eldoc, completion, and eval functionality?

**Comment by dleslie** [comment]
Then the modules are still being loaded by the `use` statements. :)

**Comment by dleslie** [comment]
Perhaps what you found is some dead code that can be removed?

**Comment by dieggsy** [comment]
Not sure - it also makes my repl look cleaner and helps me avoid some warnings about re-importing in the REPL, e.g. when evaling:
```scheme
(use numbers
     srfi-1
     srfi-13
     utils
     (prefix linear-algebra linalg-)
     srfi-113
     srfi-128
     srfi-19
     combinatorics)
```

**Comment by dieggsy** [comment]
Warnings in question:
```
Note: re-importing already imported identifier: current-time

Note: re-importing already imported identifier: time?

Note: re-importing already imported identifier: seconds->time

Note: re-importing already imported identifier: time->seconds
```

**Comment by dleslie** [comment]
Interesting.

Are prefix imports working with completion for you?

**Comment by dieggsy** [comment]
@dleslie I don't think prefix imports ever worked with completion for me, unless something has changed recently... I can test

**Comment by dieggsy** [comment]
Oh, just tested. They do seem to be.

**Comment by dleslie** [comment]
I don't expect that they will, they're a hack of Chicken's reader, AFAICT, and apropos has been completely unaware of them. But it's been many versions of apropos since I last tested.

**Comment by dleslie** [comment]
Oh nice! Hurray for dependency improvements.

**Comment by dleslie** [comment]
So, maybe we can just get rid of this `geiser-chicken-required-modules` altogether?

**Comment by dieggsy** [comment]
@dleslie It does seem that way - if you know the ins and outs of the code and expected behavior, you should probably test to make sure I'm not just missing something really big...

**Comment by dleslie** [comment]
Sure, in the meantime, I'll squash and merge your change. Thanks!

**Comment by dieggsy** [comment]
@dleslie on the other hand, if it's unneeded maybe we should keep `geiser-chicken-required-modules` but default it to nil, so people can automatically load additional modules they always want.

**Comment by jaor** [comment]
@dleslie, i've rolled down the merge and re-done it via the triggers from the official geiser repo, so that all mirrors of the repo are in sync.

**Pull request merged**
