### PR TITLE
Indentation and highlighting

### PR DESCRIPTION
**Pull request by alezost**
Hello, my current concern is that some guile things are not
indented/highlighted properly.  When I tried to fix it, I found several
other issues (for example, `geiser-chicken-extra-keywords` was not used
at all).

So the purpose of this PR is to move indentation rules and font-lock
highlighting common for all implementations to `geiser-syntax.el` and to
add more keywords/indents for guile implementation.

Some questions/notes:

- I put each keyword on a separate line and sorted the lines
  alphabetically.  I think it will be easier to maintain them this way.
  Is it OK?

- I removed indentation rules for `define-...` from `geiser-chicken.el`
  because they are not necessary, as all "defines" are handled properly
  by scheme-mode.

- I think that `set!`, `cut` and `cute` should be indented similarly in
  any implementation, and I think using a default indentation for them
  is better than using "1" as a `scheme-indent-function`.  Such
  indentation looks rather unusual IMHO, so what about removing it from
  `geiser-chicken`?  If a user likes it, he can add such indent himself.

- Why does `geiser-chicken` uses `scheme-let-indent` for several
  keywords (`let-values`, `parameterize`)?  Does Chicken differ from
  other implementations here?

  And a similar question about `match-let`: I just moved it with
  `scheme-let-indent` to `geiser-syntax.el`, although I think it should
  be "1" instead.

Thanks for the patience :-)

### CODE REVIEW

**Comment by dleslie** [comment]
IIRC, I copied the Chicken indentation rules from chicken.el, which is part of the official Chicken repository:
http://code.call-cc.org/cgi-bin/gitweb.cgi?p=chicken-core.git;a=blob_plain;f=misc/chicken.el;hb=HEAD

I think one of the maintainers later updated it with another PR.

That ```geiser-chicken-extra-keywords``` isn't used anywhere is most definitely a bug.

**Comment by alezost** [comment]
Dan Leslie (2015-09-27 13:32 +0300) wrote:

> IIRC, I copied the Chicken indentation rules from chicken.el, which
> is part of the official Chicken repository:
> http://code.call-cc.org/cgi-bin/gitweb.cgi?p=chicken-core.git;a=
> blob_plain;f=misc/chicken.el;hb=HEAD

`scheme-let-indent` is used to handle "named let", so if there are no
such things as:

(let-values foo ((a b))
  bar)

then there is no reason to use `scheme-let-indent` there.  So I would
replace it with "1".

-- 
Alex

**Comment by dleslie** [comment]
Sounds reasonable to me. :+1:

**Comment by alezost** [comment]
OK, so I've updated the last commit to remove excessive uses of `scheme-let-indent`.

**Comment by dleslie** [comment]
@jaor is the final say on merge requests, but it looks good to me.

**Comment by jaor** [comment]
thanks guys, merged!

**Pull request merged**
